---
- name: Clone specified NetBox git repository
  git:
    repo: "{{ netbox_git_uri }}"
    dest: "{{ netbox_git_repo_path }}"
    version: "{{ netbox_git_version }}"
  register: _netbox_git_repo
  become: True
  become_user: "{{ netbox_user }}"

- name: Create git deployment directory for NetBox
  file:
    path: "{{ netbox_git_deploy_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    state: directory

- name: Check existence of commit 1fb67b7, fixing issue netbox#2239
  shell: 'set -o pipefail; git log --format=%H "{{ netbox_git_version }}" | grep ^1fb67b791f1a91c624dae4a1cd256e4cf3ddbb77'
  args:
    chdir: "{{ netbox_git_repo_path }}"
    executable: /bin/bash
  register: _netbox_git_contains_issue_2239_fix
  changed_when: False
  failed_when: "_netbox_git_contains_issue_2239_fix.rc not in [0, 1]"

- name: Archive and extract snapshot of git repository
  shell: 'set -o pipefail; git archive "{{ netbox_git_version }}" | tar -x -C "{{ netbox_git_deploy_path }}"'
  args:
    chdir: "{{ netbox_git_repo_path }}"
    executable: /bin/bash
  notify:
    - reload netbox.service
  when:
    - _netbox_git_repo is changed
  become: True
  become_user: "{{ netbox_user }}"

- name: Symlink git repository to current NetBox directory
  file:
    src: "{{ netbox_git_deploy_path }}"
    dest: "{{ netbox_current_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    state: link
