galaxy_info:
  author: Musee Ullah
  description: Installs and configures NetBox, a DCIM suite, in a production setting.
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: Debian
      versions:
        - buster
        - stretch
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - dcim
    - ipam
    - web
    - networking
    - datacenter
dependencies: []
