---
# tasks file for roles/win_ad_user

- name: Create Windows Domain Group
  win_domain_group:
    name: "{{ item.group_name }}"
    scope: "{{ item.group_scope }}"
    state: present
  loop: "{{ user_info }}"
  register: domain_group

- name: debug domain_group
  debug: var=domain_group

- name: Create AD User
  win_domain_user:
    name: "{{ item.name }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    groups: "{{ item.group_name }}"
    state: present
    email: "{{ item.name }}@ad1.6ffe.example.opentlc.com"
  loop: "{{ user_info }}"
  register: ad_user

- name: debug ad_user
  debug: var=ad_user


