---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "RedHat@1313"
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "password"

#HTTP Settings
http_host: "yyz.lab.local"
http_conf: "wordpress.conf"
http_port: "80"
