- name: Gather Facts from Juniper Router
  hosts: juniper
  gather_facts: false
  collections:
    - junipernetworks.junos
  tasks:
    - name: Gather Facts
      junos_facts:
        gather_subset: min
    - name: Display Junos Version
      debug:
        var: ansible_net_version

- name: Gather Facts from F5
  hosts: f5
  gather_facts: false
  connections: local
  tasks:
    - name: Collect BIG-IP Facts
      f5networks.f5_modules.bigip_device_info: # collection path
        gather_subset:
          - system-info
        provider:
          server: "{{ ansible_host }}"
          user: "{{ ansible_user }}"
          password: "{{ ansible_ssh_pass }}"
          server_port: 8443
          validate_certs: no
        register: device_facts

    - name: Display F5 Version
      debug:
        var: device_facts['system-info']['product_version']

