- name: IOS Device Backup
  hosts: "{{ HOSTS }}"
  gather_facts: false
  tasks:
  - name: Backup IOS Device
    ios_config:
      backup: true
    register: ios_backup

  - name: archive backup
    shell: scp -o "StrictHostKeyChecking=no" -r backup/cs01* cloud-user@192.168.0.10:~/backup/

  - name: debug ios backup
    debug: var=ios_backup
