---
- name: Create or destroy EC2 instances
  ec2:
    assign_public_ip: yes
    key_name: "{{ ec2_key_name }}"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ item.instance_type }}"
    image: "{{ item.image }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ ec2_exact_count }}"
    count_tag:
      name: "{{ ec2_name_prefix }}-{{ item.pod_name | default('') }}-{{ item.role }}-{{ item.name }}"
    instance_tags:
      name: "{{ ec2_name_prefix }}-{{ item.pod_name | default('') }}-{{ item.role }}-{{ item.name }}"
      environment: "{{ environment | default('') }}"
      role: "{{ item.role }}"
      app: "{{ item.app_name }}"
      pod: "{{ item.pod_name | default('') }}"
      user: "{{ item.username | default('') }}"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id | default(omit) }}"
    user_data: "{{ item.user_data | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
  with_items:
    - "{{ nodes }}"
  register: ec2_jobs
  async: 7200
  poll: 0
  tags:
    - always
    - provision