- name: Delete OpenStack Instance
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Delete OpenStack Instance
    os_server:
      state: absent
      name: "{{ instance_name }}"
    register: os_server_delete

  - name: debug os server delete
    debug: var=os_server_delete
