- name: Launch OpenStack Instance
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Launch a New Instance with Network and Metadata
    os_server:
      state: present
      name: "{{ instance_name }}"
      image: "{{ image_name }}"
      key_name: "{{ pubkey_name }}"
      wait: yes
      flavor: "{{ flavor_name }}"
      security_groups:
       - default
       - remotesec1
      network: "{{ network_name }}"
      auto_ip: false
      userdata: "{{ lookup('template', 'templates/userdata.txt.j2') }}"
      meta:
        group=windows
    register: os_server_instance


  - name: Wait for instance creation to complete
    async_status: jid="{{ item.ansible_job_id }}"
    register: instances
    until: instances.finished
    retries: 300
    delay: 10
    with_items: "{{ os_server_instance.results }}"

  - name: Waiting for servers to come online
    wait_for:
      host: "{{ item.openstack.public_v4|default(item.openstack.interface_ip) }}"
      port: 5986
      timeout: 600
    with_items: "{{ instances.results }}"
