- name: Launch OpenStack Instance
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Launch a New Instance with Network and Metadata
    os_server:
      state: present
      name: "{{ instance_name }}"
      image: "{{ image_name }}"
      key_name: "{{ pubkey_name }}"
      wait: yes
      flavor: "{{ flavor_name }}"
      security_groups:
       - default
       - remotesec1
      network: "{{ network_name }}"
      auto_ip: false
#        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled True
#        Set-NetFirewallRule -Name 'WINRM-HTTP-In-TCP-PUBLIC' -RemoteAddress Any
      userdata: |
        #ps1
         netsh advfirewall firewall set rule name="Allow WinRM HTTPS" new profile=any
         Enable-WSManCredSSP -Role Server -Force
      meta:
        group=windows
    register: os_server_instance

  - name: debug os_server_instance
    debug: var=os_server_instance

#  - name: Add Host to a Group
#    tower_host:
#      name: "{{ os_server_instance.openstack.name }}"
#      description: Windows Host
#      inventory: OpenStack
#      state: present
#      tower_config_file: /home/cloud-user/.tower_cli.cfg
#      variables:
#        ansible_host: "{{ os_server_instance.openstack.private_v4 }}"

#  - name: Associate host group 
#    shell: tower-cli host associate  --host "{{ os_server_instance.openstack.private_v4 }}" --group windows
