- name: Launch OpenStack Instance
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Launch a New Instance with Network and Metadata
    os_server:
      state: present
      name: "{{ instance_name }}"
      image: "{{ image_name }}"
      key_name: "{{ pubkey_name }}"
      wait: yes
      flavor: "{{ flavor_name }}"
      security_groups:
       - default
       - remotesec1
      network: "{{ network_name }}"
