- name: Launch OpenStack Instance
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Launch a New Instance with Network and Metadata
    os_server:
      state: present
      name: "{{ instance_name }}"
      image: "{{ image_name }}"
      key_name: "{{ pubkey_name }}"
      wait: yes
      flavor: "{{ flavor_name }}"
      security_groups:
       - default
       - remotesec1
      network: "{{ network_name }}"
      auto_ip: false
      userdata: |
        #ps1
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
      meta:
        hostname=winad1.example.com
    register: os_server_instance

  - name: debug os_server_instance
    debug: var=os_server_instance

  - name: Associate host group 
    shell: tower-cli host associate  --host "{{os_server_instance.private_v4 }}" --group windows
