---
- name: Apache server installed
  hosts: "{{ HOSTS }}"
  become: true
  tasks:

  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: copy index.html
    copy:
      content: Apache is running fine
      dest: /var/www/html/index.html


  - name: debug the host IP
    debug:
      msg: "http://{{ansible_fqdn}}"
