- name: Register Clients to Red Hat Satellite
  hosts: all
  tasks:

#  - name: Unregister Any old registration
#    redhat_subscription:
#      state: absent
  - name: Disable all the repos
    shell: subscription-manager repos --disable='*'

  - name: Uninstall Consumer RPMS
    shell: rpm -e katello-ca-consumer-satellite6.example.com-1.0-1.noarch
    ignore_errors: true

  - name: Install Red Hat Satellite Consumer RPM
    shell: rpm -Uvh http://192.168.0.9/pub/katello-ca-consumer-latest.noarch.rpm

  - name: Run the registration on RHEL7 Clients
    redhat_subscription:
      state: present
      org_id: "RHCanada"
      activationkey: rhel7base-ak
      force_register: true
    when: ansible_distribution_major_version == "7"

  - name: Run the registration on RHEL8 Clients
    redhat_subscription:
      state: present
      org_id: "RHCanada"
      activationkey: rhel8base-ak
      force_register: true
    when: ansible_distribution_major_version == "8"

  - name: Install Satellite Agent and Red Hat Insights
    yum:
      name:
        - katello-agent
        - katello-host-tools-tracer
        - insights-client
      state: present

  - name: Register RH Insights
    shell: insights-client --register

  - name: Collect insights data
    shell: insights-client

