- name: Manage Local User on Windows
  hosts: "{{ HOSTS }}"
  tasks:
  - name: Local User {{ user_name }} is {{ user_state }}
    win_user:
      name: "{{ user_name }}"
      state: "{{ user_state }}"
      password: "{{ user_password }}"
    no_log: true
