- name: Manage Local User on Windows
  hosts: "{{ HOSTS }}"
  tasks:
  - name: {{ user_state }} {{ user_name }} Local User
    win_user:
      name: "{{ user_name }}"
      state: "{{ user_state }}"
      password: "{{ user_password }}"
    no_log: true
