- name: Install IIS Service
  hosts: "{{ HOSTS }}"
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Install IIS Service
    win_feature:
      name: Web-Server
      state: present
  - name: Start IIS Service
    win_service:
       name: W3Svc
       state: started
  - name: IIS Welcome Page
    win_copy:
       src: files/index.html
      # content: "Hello from {{ ansible_facts['fqdn']\n }}"
       dest: C:\Inetpub\wwwroot\index.html

  - name: IIS Pic Update 1
    win_copy:
       src: files/Arjun_Ansible-1.jpeg
       dest: C:\Inetpub\wwwroot\Arjun_Ansible-1.jpeg

  - name: IIS Pic Update 2
    win_copy:
       src: files/Arjun_Ansible-2.jpeg
       dest: C:\Inetpub\wwwroot\Arjun_Ansible-2.jpeg

  - name: Firewall rule to allow HTTP on TCP port 80
    win_firewall_rule:
      name: HTTP
      localport: 80
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
  - name: Display the web url
    debug:
      msg: "http://{{ ansible_host }}"
