- name: Update Windows System
  hosts: all
  tasks:
  - name: Apply Critical Updates, reboot if required
    win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: "{{ reboot_server | default(yes) }}"
