- name: Update Windows System
  hosts: "{{ HOSTS }}"
  tasks:
  - name: Apply Critical Updates, reboot if required
    win_updates:
        category_names: "{{ categories | default(omit) }}"
        reboot: "{{ reboot_server | default(yes) }}"
        log_path: C:\ansible_wu.txt
