- name: Remove VM
  hosts: localhost
  gather_facts: no
  tasks:
   - name: Remove a virtual machine by uuid
     vmware_guest:
       hostname: "{{ vcenter_hostname }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       name: "{{ vm_name }}"
       state: absent
     delegate_to: localhost
