- name: Deploy a Virtual Machine on vSphere
  hosts: localhost
  gather_facts: no
  tasks:

  - name: Create a virtual machine from a template
    vmware_guest:
      validate_certs: no
      datacenter: RHToronto
      cluster: Shadowman
      folder: /AnsibleAutomation
      name: "{{ instance_name }}"
      state: poweredon
      template: RHEL8
      disk:
      - size_gb: 10
        type: thin
        datastore: LocalSSD
      hardware:
        memory_mb: 512
        num_cpus: 1
#        max_connections: 5
#        hotadd_cpu: True
#        hotremove_cpu: True
#        hotadd_memory: False
      networks:
      - name: VM Network
        ip: "{{ instance_ip }}"
        netmask: 255.255.255.0
        gateway: 192.168.100.100
        type: static
      wait_for_ip_address: true
    delegate_to: localhost
    register: vm_deploy

  - name: show debug
    debug: var=vm_deploy
