---
- hosts: vcenter.yyz.lab.local
  gather_facts: no
  vars:
    vcenter_server: "192.168.100.252"
    vcenter_user: "administrator@vsphere.local"
    vcenter_pass: "{{ vcenterpass }}"
    datacenter_name: "RHToronto"
    cluster_name: "Shadowman"
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_server }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: False
      name: "{{ instance_name }}"
      template: "{{ template }}"
      datacenter: "{{ datacenter_name }}"
      folder: /{{ ansibleprovisioned }}/vm
      cluster: "{{ cluster_name }}"
      datastore: "LocalSSD"
      networks:
      - name: VM Network
        ip: "{{ ip_address }}"
        netmask: 255.255.255.0
        gateway: 192.168.100.100
        type: static
        dns_servers: 192.168.100.254
      customization:
        hostname: "{{ hostname }}"
        dns_servers:
        - 192.168.100.254
        - 8.8.8.8
      state: poweredon
      wait_for_ip_address: yes
    delegate_to: localhost
