- name: Deploy Windows AD Instances on OpenStack
  hosts: localhost
  gather_facts: False
  connection: local
  become: no
  vars_files:
    - node-config/ad-node-openstack.yml
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    ansible_port: 5986
    windows: yes
  roles:
    - ansible-role-os-stack