- name: remove computer object to the domain
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: ad-computer-registration
      role_action: deregister