- name: Remove Windows Cluster Servers
  hosts: all
  gather_facts: False
  connection: local
  vars:
    ansible_ssh_password: ''
  become: no
  vars_files:
    - node-config/cluster-nodes-vmware.yml

  roles:
    - role: ansible-role-vmware
      role_action: deprovision
      delegate_to: localhost