---

- name: Fix a broken Service
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm

  tasks:
    - name: Fix Print Spooler Service
      win_service:
        name: Spooler
        username: LocalSystem
        password: ""
        state: started
        start_mode: auto