- name: Install IIS with DSC
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
    install_with: ini
  roles:
    - iis-dsc
