- name: Install SQL 2016
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_transport: credssp
    ansible_winrm_server_cert_validation: ignore
  roles:
    - role: mcafee-epo
      sql_server_hostname: "{{ ansible_host | default(ansible_ssh_host) | default(inventory_hostname) }}"